FROM node:22-alpine as builder

ARG NODE_ENV="develop"
ENV NODE_ENV=$NODE_ENV
ENV NODE_OPTIONS="--max-old-space-size=4096"

ARG REACT_APP_API_URL=$REACT_APP_API_URL

ENV REACT_APP_API_URL=$REACT_APP_API_URL

# /app 디렉토리 생성
RUN mkdir -p /app

# 현재 Dockerfile 있는 경로의 모든 파일을 /app 에 복사
COPY ./ ./app

# /app 디렉토리를 WORKDIR 로 설정
WORKDIR /app

RUN ./makeenv.sh

#가상 머신에 오픈할 포트
EXPOSE 3000

# npm install
RUN yarn install

# 개발 서버 실행
CMD ["yarn", "start:dev"]
